### ISSUE TITLE
remove `url` dependency

### ISSUE THREAD

**Issue by refractalize** [featurist/routism#1]
This code: https://github.com/featurist/routism/blob/master/src/routism.pogo#L33-L35

Does a `require 'url'` which, when browserified, brings in a lot of new code, about 40k worth. Think we could just use a regex for this bit.

**Comment by joshski** [comment]
Oh yeah, dumb!

**Comment by joshski** [comment]
Fixed in https://github.com/featurist/routism/commit/e18bf81a295da33b7c8427585ebf5d7ad93bdf28 and released as 0.0.5
